### ISSUE TITLE
Ensure AI planes spawn at ramps

### ISSUE THREAD

**Issue by togfoxy** [felix-b/atc#186]
AI planes need to spawn at ramps (in prep for departure) in a random way. This involves:
- understand the current airport the player is at
- understanding the available gates/ramps
- determining which gates/ramps can and will spawn an AI plane
- determining which plane will be spawned
- spawning that plane
- ensuring another plane doesn't spawn there (two planes at one gate/ramp)

**Comment by felix-b** [comment]
Current status (as of demo # 3):

- understand the current airport the player is at - TODO
- understanding the available gates/ramps - DONE
- determining which gates/ramps can and will spawn an AI plane - DONE but can be improved to account for specific airlines
- determining which plane will be spawned - TODO: currently B738 is always spawned (will post a separate comment on that)
- spawning that plane - DONE
- ensuring another plane doesn't spawn there (two planes at one gate/ramp) - DONE, must be maintained through the progress

**Comment by felix-b** [comment]
What's necessary to allow multiple aircraft models:
- the user will have to download a full CSL package. In #15 (nightly build) I put B738 with all available liveries into a ZIP - so B738 can work out of the box, but that's all
- every model has to be configured with a vertical offset and a pitch angle to correctly position it on the ground, otherwise some wheels get sunken into the ground while some are hanging in the air: https://forums.x-plane.org/index.php?/forums/topic/214646-xpmp2-library/&tab=comments#comment-2008952  (you can see what happened to A320)

**Comment by felix-b** [comment]
I think an additional bullet is:
- generate a random flight schedule with departures (and arrivals?) from/to the airport

**Comment by togfoxy** [comment]
Repeating in this issue:

navref = XPLMFindNavAid( nil, nil, LATITUDE, LONGITUDE, nil, xplm_Nav_Airport)

will return an ICAO code for the players closest (current) airport.

**Comment by togfoxy** [comment]
When starting at a large airport (YBBN) some planes will spawn at only a few ramps. I would expect a lot more ramps to spawn planes.

**Comment by togfoxy** [comment]
From Felix:
I always take 10 first gates in the order they appear in apt.dat
the even one for arrivals, and the odd ones for departures

**Comment by togfoxy** [comment]
Should this be closed? The issue seems to be 'done'.

**Comment by felix-b** [comment]
Yep, closing this one
